### ISSUE TITLE
Dashboard Map - Pin Colors are Reversed -- Green <--> Blue

### ISSUE THREAD

**Issue by dodget** [AASHE/stars#256]
Per Chris: 
- The map looks great, but there appear to be too many green dots (unrated institutions with a full access subscription) and too few blue dots (unrated institutions with basic access).

- Participants by Country. Is it possible to move the STARS pins to the front for emphasis and easier access (i.e. display in front of green and blue dots)? This a really minor and probably not worth spending a lot of time on.

- If you have to do another merge, Julian has suggested changing "Participants" in the chart to "Registrants" to better distinguish them from "Active Participants". It's not important enough to do another round of revisions just for that though.

**Comment by peltonc** [comment]
Closed because map is non-functional.
