### ISSUE TITLE
Set up STARS db backups

### ISSUE THREAD

**Issue by rerb** [AASHE/stars#276]
1. mysql dump in same format Sequel Pro exports.
2. zip and send to s3 -- use kenneth reitz's new s3 as a filesystem package
3. set up cronicle to rotate backups on s3 -- or mirror subdirectory on stars.aashe.org to s3 folder, do rotation on local file system, then sync folder to s3

**Comment by Rogelio-AASHE** [comment]
stale to be redefined by Chris and Ro
