### ISSUE TITLE
Match figures in the Dashboard and Participant Reports table

### ISSUE THREAD

**Issue by peltonc** [AASHE/stars#402]
The [data displays dashboard](https://reports.aashe.org/institutions/data-displays/dashboard/) does not match what is in the Participant Reports table.

Level | Participants and Reports table | Data Display Dashboard
-- | -- | --
Reporter | 13 | 10
Bronze | 51 | 54
Silver | 138 | 139
Gold | 130 | 129
Platinum | 5 | 5
Rated Institutions | 337 | 333

**Comment by dodget** [comment]
This is turning out to be a bit confusing. From my initial look, it appears that an institution's `current_rating` is not necessarily correct. I'm not sure why that field really exists. It seems to be a denormalization of data for quicker access. In this case however, it is just causing confusion.

**Comment by dodget** [comment]
To be clear:
the participants and reports table is referencing
Institution -> rated_submission -> rating name -> expired?

The dashboard is looking for data in this way:
Institution -> current_rating

**Comment by dodget** [comment]
Ok, I think I have it worked out, and it is pushed to the `benchmarking-charts` branch. I'll issue a PR, but the branch should be tested on dev thoroughly.

**Comment by peltonc** [comment]
Will the change still ensure that a Reporter submission does not overwrite an existing Bronze, Silver, Gold or Platinum rating?
