### ISSUE TITLE
Redirect https://reports.aashe.org

### ISSUE THREAD

**Issue by peltonc** [AASHE/stars#405]
Redirect https://reports.aashe.org to either [Participant Reports](https://reports.aashe.org/institutions/participants-and-reports/) or the [Reporting Tool](https://reports.aashe.org/tool/).

**Comment by dodget** [comment]
I've set it up to redirect to `/tool` which will bring users to the Reporting Tool. I've removed the old view along with the corresponding templates.

This has been pushed to the `benchmarking-charts` branch.
